name: estructuratrabajofinal
description: "Peluqueria"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  table_calendar: ^3.1.3
  intl: any
  fluttertoast: ^8.0.9
  fl_chart: ^0.70.2
  shared_preferences: ^2.5.1
  provider: ^6.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/  
